### ISSUE TITLE
Run failed:segmentation fault (core dumped).

### ISSUE THREAD

**Issue by CrisGao** [yanyan-li/PlanarSLAM#1]
![image](https://user-images.githubusercontent.com/32894619/103339995-e66b5400-4abd-11eb-8424-074cd6805bd2.png)

When I run the ICL NUIM or TUM rgdb datasets, the following error will be reported.

**Comment by yanyan-li** [comment]
Thanks for testing the system. 
Currently, it's still under cleaning. We planed to release all files at the beginning of 2021.

**Comment by CrisGao** [comment]
@yanyan-li 
Thank you for making your project open source. It can run after commenting the threadPlanes() in Frame.cc.
Looking forward to your entire project.
Best wishes~

**Comment by CrisGao** [comment]
@yanyan-li Happy new year

I guess you have updated all the code. I pulled and compiled the code,but the same problem still occurs. According to the gdb information, it may be a problem of  memory free.
![Screenshot from 2021-01-04 15-44-03](https://user-images.githubusercontent.com/32894619/103513125-ee077000-4ea4-11eb-8759-9ed8703b9fc8.png)

 I guess there is a problem with variable "coarseCloud" and "ne" in the void Frame::ComputePlanes() in Frame.cc 

`PointCloud::Ptr coarseCloud(new PointCloud());`
`pcl::IntegralImageNormalEstimation<PointT, pcl::Normal> ne;`

I tried to write it as a global variable, the system can only be run once, and the error occurs the second time. I have no ideas,Hope to get your help

**Comment by yanyan-li** [comment]
> @yanyan-li Happy new year
> 
> I guess you have updated all the code. I pulled and compiled the code,but the same problem still occurs. According to the gdb information, it may be a problem of memory free.
> ![Screenshot from 2021-01-04 15-44-03](https://user-images.githubusercontent.com/32894619/103513125-ee077000-4ea4-11eb-8759-9ed8703b9fc8.png)
> 
> I guess there is a problem with variable "coarseCloud" and "ne" in the void Frame::ComputePlanes() in Frame.cc
> 
> `PointCloud::Ptr coarseCloud(new PointCloud());`
> `pcl::IntegralImageNormalEstimation<PointT, pcl::Normal> ne;`
> 
> I tried to write it as a global variable, the system can only be run once, and the error occurs the second time. I have no ideas,Hope to get your help

Happy new year.
Those functions work well in my laptop. Maybe the version of PCL? We tried 1.7.0 and 1.9.0.

**Comment by match08** [comment]
Run failed:segmentation fault (core dumped)
run TUM error
