### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by Xuheyi** [yanyan-li/PlanarSLAM#13]
Excuse me，
Why are the displayed keypoints so small, did you use an algorithm to improve the feature points? If not, can you tell me how to set it up? I want him to be as big as the key point of ORB-SLAM2. Thank you very much!

**Comment by yanyan-li** [comment]
Hi @Xuheyi , Thanks for your testing. You could modify those image visualization blocks here (src/FrameDrawer.cc), including colors and size.
