### ISSUE TITLE
针对奥比中光深度相机的平面调参技巧，以及living_room数据集格式问题

### ISSUE THREAD

**Issue by why-freedom** [yanyan-li/PlanarSLAM#2]
# 请问使用实际相机测试发现平面上的点不如论文中的密集。这种情况应该怎么调节参数？
环境：ubuntu16.04
相机：奥比中光astrapro 深度相机

**Comment by why-freedom** [comment]
请问living_room数据格式和tum不一样，我尝试自己写associte将其关联，但是名称并不是时间戳，所以会报错。您可以提供相关的工具包或者数据吗

**Comment by yanyan-li** [comment]
Hi, Thanks for testing our system.

**Comment by yanyan-li** [comment]
> 请问living_room数据格式和tum不一样，我尝试自己写associte将其关联，但是名称并不是时间戳，所以会报错。您可以提供相关的工具包或者数据吗
If you have the correct rgb.txt and depth.txt files, the TUM RGB-D [tool] (https://vision.in.tum.de/data/datasets/rgbd-dataset/tools) can help you generate a correct assocition.txt file.  Another simple way is to swap the names of depth and rgb forders.
